const VERSES = [
  { text: 'El Señor es mi pastor, nada me falta.', ref: 'Salmos 23:1' },
  { text: 'Todo lo puedo en Cristo que me fortalece.', ref: 'Filipenses 4:13' },
  { text: 'Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito.', ref: 'Juan 3:16' },
  { text: 'No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios.', ref: 'Isaías 41:10' },
  { text: 'El Señor te bendiga y te guarde.', ref: 'Números 6:24' },
  { text: 'Confía en el Señor con todo tu corazón.', ref: 'Proverbios 3:5' },
  { text: 'En paz me acostaré y asimismo dormiré, porque solo tú, Señor, me haces vivir confiado.', ref: 'Salmos 4:8' },
  { text: 'El Señor es mi luz y mi salvación; ¿de quién temeré?', ref: 'Salmos 27:1' },
  { text: 'Bueno es el Señor para con todos.', ref: 'Salmos 145:9' },
  { text: 'Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.', ref: 'Mateo 11:28' },
  { text: 'El amor nunca deja de ser.', ref: '1 Corintios 13:8' },
  { text: 'Mas los que esperan a Jehová tendrán nuevas fuerzas.', ref: 'Isaías 40:31' },
  { text: 'Regocijaos en el Señor siempre. Otra vez digo: ¡Regocijaos!', ref: 'Filipenses 4:4' },
  { text: 'Por nada estéis afanosos, sino sean conocidas vuestras peticiones delante de Dios.', ref: 'Filipenses 4:6' },
  { text: 'Y conoceréis la verdad, y la verdad os hará libres.', ref: 'Juan 8:32' },
  { text: 'El que habita al abrigo del Altísimo morará bajo la sombra del Omnipotente.', ref: 'Salmos 91:1' },
  { text: 'Grande es tu fidelidad.', ref: 'Lamentaciones 3:23' },
  { text: 'Jehová es mi roca y mi fortaleza.', ref: 'Salmos 18:2' },
  { text: 'Bendice, alma mía, a Jehová, y no olvides ninguno de sus beneficios.', ref: 'Salmos 103:2' },
  { text: 'El Señor está cerca de los quebrantados de corazón.', ref: 'Salmos 34:18' },
  { text: 'Fíate de Jehová de todo tu corazón.', ref: 'Proverbios 3:5' },
  { text: 'Esforzaos y cobrad ánimo; no temáis, porque Jehová tu Dios estará contigo.', ref: 'Josué 1:9' },
  { text: 'Clama a mí, y yo te responderé.', ref: 'Jeremías 33:3' },
  { text: 'El camino de Dios es perfecto.', ref: 'Salmos 18:30' },
  { text: 'Jehová es mi pastor; nada me faltará.', ref: 'Salmos 23:1' },
  { text: 'Someteos a Dios; resistid al diablo, y huirá de vosotros.', ref: 'Santiago 4:7' },
  { text: 'Porque yo sé los pensamientos que tengo acerca de vosotros, pensamientos de paz.', ref: 'Jeremías 29:11' },
  { text: 'El que comenzó en vosotros la buena obra la perfeccionará.', ref: 'Filipenses 1:6' },
  { text: 'Dios es nuestro amparo y fortaleza.', ref: 'Salmos 46:1' },
  { text: 'Alégrate, joven, en tu juventud.', ref: 'Eclesiastés 11:9' },
  { text: 'El temor de Jehová es el principio de la sabiduría.', ref: 'Proverbios 9:10' },
  { text: 'Pedid, y se os dará; buscad, y hallaréis.', ref: 'Mateo 7:7' },
  { text: 'Bienaventurados los mansos, porque ellos recibirán la tierra por heredad.', ref: 'Mateo 5:5' },
  { text: 'Vosotros sois la luz del mundo.', ref: 'Mateo 5:14' },
  { text: 'Amad a vuestros enemigos.', ref: 'Mateo 5:44' },
  { text: 'No os afanéis por el día de mañana.', ref: 'Mateo 6:34' },
  { text: 'Buscad primeramente el reino de Dios.', ref: 'Mateo 6:33' },
  { text: 'Con tus ojos contemplarás la recompensa de los impíos.', ref: 'Salmos 91:8' },
  { text: 'Jehová guarda a todos los que le aman.', ref: 'Salmos 145:20' },
  { text: 'Grandes son las obras de Jehová.', ref: 'Salmos 111:2' },
  { text: 'El principio de la sabiduría es el temor de Jehová.', ref: 'Salmos 111:10' },
  { text: 'Jehová es grande y digno de suprema alabanza.', ref: 'Salmos 145:3' },
  { text: 'Cercano está Jehová a todos los que le invocan.', ref: 'Salmos 145:18' },
  { text: 'El Señor levanta a los caídos.', ref: 'Salmos 146:8' },
  { text: 'Canta alegres a Dios, habitantes de toda la tierra.', ref: 'Salmos 100:1' },
  { text: 'Servid a Jehová con alegría.', ref: 'Salmos 100:2' },
  { text: 'Jehová es bueno; para siempre es su misericordia.', ref: 'Salmos 100:5' },
  { text: 'Bendito sea Jehová para siempre.', ref: 'Salmos 89:52' },
  { text: 'Jehová es nuestro refugio y fortaleza.', ref: 'Salmos 46:1' },
  { text: 'Estad quietos, y conoced que yo soy Dios.', ref: 'Salmos 46:10' },
  { text: 'Pueblos todos, batid palmas.', ref: 'Salmos 47:1' },
  { text: 'Grande es Jehová y digno de ser alabado.', ref: 'Salmos 48:1' },
  { text: 'El Dios eterno es tu refugio.', ref: 'Deuteronomio 33:27' },
  { text: 'Jehová va delante de ti.', ref: 'Deuteronomio 31:8' },
  { text: 'No te dejaré, ni te desampararé.', ref: 'Hebreos 13:5' },
  { text: 'Jesucristo es el mismo ayer, hoy y por los siglos.', ref: 'Hebreos 13:8' },
  { text: 'Acerquémonos confiadamente al trono de la gracia.', ref: 'Hebreos 4:16' },
  { text: 'La fe es la certeza de lo que se espera.', ref: 'Hebreos 11:1' },
  { text: 'Sin fe es imposible agradar a Dios.', ref: 'Hebreos 11:6' },
  { text: 'Toda buena dádiva proviene de lo alto.', ref: 'Santiago 1:17' },
  { text: 'Sed hacedores de la palabra, y no tan solamente oidores.', ref: 'Santiago 1:22' },
  { text: 'La religión pura es visitar a los huérfanos y a las viudas.', ref: 'Santiago 1:27' },
  { text: 'La fe sin obras es muerta.', ref: 'Santiago 2:26' },
  { text: 'Humillaos delante del Señor, y él os exaltará.', ref: 'Santiago 4:10' },
  { text: 'La oración del justo puede mucho.', ref: 'Santiago 5:16' },
  { text: 'Dios resiste a los soberbios, y da gracia a los humildes.', ref: '1 Pedro 5:5' },
  { text: 'Echad toda vuestra ansiedad sobre él.', ref: '1 Pedro 5:7' },
  { text: 'El Señor sabe librar de tentación a los piadosos.', ref: '2 Pedro 2:9' },
  { text: 'Si confesamos nuestros pecados, él es fiel para perdonarnos.', ref: '1 Juan 1:9' },
  { text: 'Dios es amor.', ref: '1 Juan 4:8' },
  { text: 'En el amor no hay temor.', ref: '1 Juan 4:18' },
  { text: 'El que permanece en amor permanece en Dios.', ref: '1 Juan 4:16' },
  { text: 'Esta es la victoria que vence al mundo: nuestra fe.', ref: '1 Juan 5:4' },
  { text: 'Yo estoy contigo todos los días.', ref: 'Mateo 28:20' },
  { text: 'Id por todo el mundo y predicad el evangelio.', ref: 'Marcos 16:15' },
  { text: 'Para Dios todo es posible.', ref: 'Marcos 10:27' },
  { text: 'Amarás al Señor tu Dios con todo tu corazón.', ref: 'Marcos 12:30' },
  { text: 'Amarás a tu prójimo como a ti mismo.', ref: 'Marcos 12:31' },
  { text: 'No juzguéis, y no seréis juzgados.', ref: 'Lucas 6:37' },
  { text: 'Dad, y se os dará.', ref: 'Lucas 6:38' },
  { text: 'El Hijo del Hombre vino a buscar y salvar lo que se había perdido.', ref: 'Lucas 19:10' },
  { text: 'Nada hay imposible para Dios.', ref: 'Lucas 1:37' },
  { text: 'Gloria a Dios en las alturas, y en la tierra paz.', ref: 'Lucas 2:14' },
  { text: 'En el principio era el Verbo, y el Verbo era con Dios.', ref: 'Juan 1:1' },
  { text: 'A todos los que le recibieron les dio potestad de ser hijos de Dios.', ref: 'Juan 1:12' },
  { text: 'De tal manera amó Dios al mundo.', ref: 'Juan 3:16' },
  { text: 'El que cree en mí tiene vida eterna.', ref: 'Juan 6:47' },
  { text: 'Yo soy el pan de vida.', ref: 'Juan 6:35' },
  { text: 'Yo soy la luz del mundo.', ref: 'Juan 8:12' },
  { text: 'Yo soy la resurrección y la vida.', ref: 'Juan 11:25' },
  { text: 'Yo soy el camino, la verdad y la vida.', ref: 'Juan 14:6' },
  { text: 'La paz os dejo, mi paz os doy.', ref: 'Juan 14:27' },
  { text: 'Permaneced en mi amor.', ref: 'Juan 15:9' },
  { text: 'Nadie tiene mayor amor que este, que uno ponga su vida por sus amigos.', ref: 'Juan 15:13' },
  { text: 'En el mundo tendréis aflicción, pero confiad, yo he vencido al mundo.', ref: 'Juan 16:33' },
  { text: 'Santifícalos en tu verdad; tu palabra es verdad.', ref: 'Juan 17:17' },
  { text: 'Recibid el Espíritu Santo.', ref: 'Juan 20:22' },
  { text: 'Bienaventurados los que no vieron y creyeron.', ref: 'Juan 20:29' },
  { text: 'Ruego por ellos; no ruego por el mundo, sino por los que me diste.', ref: 'Juan 17:9' },
  { text: 'No se turbe vuestro corazón; creéis en Dios, creed también en mí.', ref: 'Juan 14:1' },
  { text: 'Recibiréis poder cuando haya venido sobre vosotros el Espíritu Santo.', ref: 'Hechos 1:8' },
  { text: 'Arrepiéntanse y bautícese cada uno de vosotros en el nombre de Jesucristo.', ref: 'Hechos 2:38' },
  { text: 'No tengo plata ni oro, pero lo que tengo te doy: en el nombre de Jesucristo, levántate y anda.', ref: 'Hechos 3:6' },
  { text: 'Es necesario obedecer a Dios antes que a los hombres.', ref: 'Hechos 5:29' },
  { text: 'Señor, ¿qué quieres que yo haga?', ref: 'Hechos 9:6' },
  { text: 'Dios no hace distinción de personas.', ref: 'Hechos 10:34' },
  { text: 'El justo por la fe vivirá.', ref: 'Romanos 1:17' },
  { text: 'Todos pecaron y están destituidos de la gloria de Dios.', ref: 'Romanos 3:23' },
  { text: 'El don de Dios es vida eterna en Cristo Jesús.', ref: 'Romanos 6:23' },
  { text: 'Ninguna condenación hay para los que están en Cristo Jesús.', ref: 'Romanos 8:1' },
  { text: 'La ley del Espíritu de vida te ha librado de la ley del pecado.', ref: 'Romanos 8:2' },
  { text: 'Si Dios es por nosotros, ¿quién contra nosotros?', ref: 'Romanos 8:31' },
  { text: 'En todas estas cosas somos más que vencedores.', ref: 'Romanos 8:37' },
  { text: 'Ninguna cosa creada nos podrá separar del amor de Dios.', ref: 'Romanos 8:39' },
  { text: 'No te dejes vencer por el mal; vence con el bien.', ref: 'Romanos 12:21' },
  { text: 'Ama a tu prójimo como a ti mismo.', ref: 'Romanos 13:9' },
  { text: 'El reino de Dios es justicia, paz y gozo en el Espíritu Santo.', ref: 'Romanos 14:17' },
  { text: 'A Dios gracias, que nos da la victoria.', ref: '1 Corintios 15:57' },
  { text: 'Sed firmes y constantes en la obra del Señor.', ref: '1 Corintios 15:58' },
  { text: 'El amor es paciente, es bondadoso.', ref: '1 Corintios 13:4' },
  { text: 'Todo lo soporta, todo lo cree, todo lo espera, todo lo soporta.', ref: '1 Corintios 13:7' },
  { text: 'Si alguno está en Cristo, nueva criatura es.', ref: '2 Corintios 5:17' },
  { text: 'Dios ama al dador alegre.', ref: '2 Corintios 9:7' },
  { text: 'Bástate mi gracia, porque mi poder se perfecciona en la debilidad.', ref: '2 Corintios 12:9' },
  { text: 'Andad en el Espíritu, y no satisfagáis los deseos de la carne.', ref: 'Gálatas 5:16' },
  { text: 'El fruto del Espíritu es amor, gozo, paz.', ref: 'Gálatas 5:22' },
  { text: 'No nos cansemos de hacer el bien.', ref: 'Gálatas 6:9' },
  { text: 'Por gracia sois salvos por medio de la fe.', ref: 'Efesios 2:8' },
  { text: 'Somos hechura suya, creados en Cristo Jesús para buenas obras.', ref: 'Efesios 2:10' },
  { text: 'Cristo es nuestra paz.', ref: 'Efesios 2:14' },
  { text: 'Sed benignos unos con otros, misericordiosos, perdonándoos.', ref: 'Efesios 4:32' },
  { text: 'Andad en amor, como también Cristo nos amó.', ref: 'Efesios 5:2' },
  { text: 'Vestíos de toda la armadura de Dios.', ref: 'Efesios 6:11' },
  { text: 'Sobrellevad los unos las cargas de los otros.', ref: 'Gálatas 6:2' },
  { text: 'Cristo nos redimió de la maldición de la ley.', ref: 'Gálatas 3:13' },
  { text: 'Ya no soy yo quien vive, sino que Cristo vive en mí.', ref: 'Gálatas 2:20' },
  { text: 'El que siembra escasamente, también segará escasamente.', ref: '2 Corintios 9:6' },
  { text: 'No os entristezcáis, porque el gozo de Jehová es vuestra fuerza.', ref: 'Nehemías 8:10' },
  { text: 'Encomienda a Jehová tus obras, y tus pensamientos serán afirmados.', ref: 'Proverbios 16:3' },
  { text: 'Corona de los viejos son los nietos.', ref: 'Proverbios 17:6' },
  { text: 'Hay amigo más unido que un hermano.', ref: 'Proverbios 18:24' },
  { text: 'El que perdona la ofensa cultiva el amor.', ref: 'Proverbios 17:9' },
  { text: 'El que guarda su boca guarda su alma.', ref: 'Proverbios 13:3' },
  { text: 'La respuesta suave quita la ira.', ref: 'Proverbios 15:1' },
  { text: 'El corazón alegre constituye buen remedio.', ref: 'Proverbios 17:22' },
  { text: 'Mejor es la comida de verduras donde hay amor.', ref: 'Proverbios 15:17' },
  { text: 'El nombre de Jehová es torre fuerte.', ref: 'Proverbios 18:10' },
  { text: 'La bendición de Jehová enriquece.', ref: 'Proverbios 10:22' },
  { text: 'El que anda en justicia anda en seguridad.', ref: 'Proverbios 10:9' },
  { text: 'La mujer virtuosa es corona de su marido.', ref: 'Proverbios 12:4' },
  { text: 'El que cubre la falta halla amor.', ref: 'Proverbios 17:9' },
  { text: 'Engañosa es la gracia y vana la hermosura.', ref: 'Proverbios 31:30' },
  { text: 'La mujer que teme a Jehová será alabada.', ref: 'Proverbios 31:30' },
  { text: 'Dadle del fruto de sus manos.', ref: 'Proverbios 31:31' },
  { text: 'El que confía en Jehová será prosperado.', ref: 'Proverbios 28:25' },
  { text: 'Honra a Jehová con tus bienes.', ref: 'Proverbios 3:9' },
  { text: 'No te olvides de mi ley, y tu corazón guarde mis mandamientos.', ref: 'Proverbios 3:1' },
  { text: 'Así alumbre vuestra luz delante de los hombres.', ref: 'Mateo 5:16' },
  { text: 'No solo de pan vivirá el hombre, sino de toda palabra de Dios.', ref: 'Lucas 4:4' },
  { text: 'La hierba se seca, la flor se marchita, mas la palabra de Dios permanece.', ref: 'Isaías 40:8' },
  { text: 'Te haré entender y te enseñaré el camino.', ref: 'Salmos 32:8' },
  { text: 'El ángel de Jehová acampa alrededor de los que le temen.', ref: 'Salmos 34:7' },
  { text: 'Gustad y ved que es bueno Jehová.', ref: 'Salmos 34:8' },
  { text: 'Jehová redime el alma de sus siervos.', ref: 'Salmos 34:22' },
  { text: 'Encomienda a Jehová tu camino, confía en él.', ref: 'Salmos 37:5' },
  { text: 'Los mansos heredarán la tierra.', ref: 'Salmos 37:11' },
  { text: 'Jehová afirma los pasos del hombre.', ref: 'Salmos 37:23' },
  { text: 'Espera en Jehová y guarda su camino.', ref: 'Salmos 37:34' },
  { text: 'Jehová es mi fortaleza y mi escudo.', ref: 'Salmos 28:7' },
  { text: 'La voz de Jehová es poderosa.', ref: 'Salmos 29:4' },
  { text: 'Jehová dará poder a su pueblo.', ref: 'Salmos 29:11' },
  { text: 'Por la noche durarán sus lágrimas, y a la mañana la alegría.', ref: 'Salmos 30:5' },
  { text: 'En ti, oh Jehová, he confiado.', ref: 'Salmos 31:1' },
  { text: 'Tú eres mi roca y mi fortaleza.', ref: 'Salmos 31:3' },
  { text: 'En tus manos encomiendo mi espíritu.', ref: 'Salmos 31:5' },
  { text: 'Esforzaos y tome aliento vuestro corazón.', ref: 'Salmos 31:24' },
  { text: 'Bienaventurado aquel cuya transgresión ha sido perdonada.', ref: 'Salmos 32:1' },
  { text: 'Muchas son las aflicciones del justo, pero de todas le librará Jehová.', ref: 'Salmos 34:19' },
  { text: 'Jehová guarda todos sus huesos.', ref: 'Salmos 34:20' },
  { text: 'Pon tu esperanza en Jehová.', ref: 'Salmos 27:14' },
  { text: 'Jehová es mi fortaleza y mi escudo.', ref: 'Salmos 28:7' },
  { text: 'La tierra está llena de la misericordia de Jehová.', ref: 'Salmos 33:5' },
  { text: 'Los ojos de Jehová están sobre los justos.', ref: 'Salmos 34:15' },
  { text: 'El Señor levantó el cielo con su palabra.', ref: 'Salmos 33:6' },
  { text: 'Bienaventurada la nación cuyo Dios es Jehová.', ref: 'Salmos 33:12' },
  { text: 'Él es quien perdona todas tus iniquidades.', ref: 'Salmos 103:3' },
  { text: 'Jehová hace justicia y derecho a todos los oprimidos.', ref: 'Salmos 103:6' },
  { text: 'Como el padre se compadece de los hijos, se compadece Jehová.', ref: 'Salmos 103:13' },
  { text: 'La misericordia de Jehová es desde la eternidad hasta la eternidad.', ref: 'Salmos 103:17' },
  { text: 'Bendecid a Jehová, vosotras todas sus obras.', ref: 'Salmos 103:22' },
  { text: 'Alabad a Jehová porque él es bueno.', ref: 'Salmos 106:1' },
  { text: 'Dad gracias a Jehová, porque él es bueno.', ref: 'Salmos 107:1' },
  { text: 'Clamaron a Jehová en su angustia.', ref: 'Salmos 107:6' },
  { text: 'Alaben la misericordia de Jehová.', ref: 'Salmos 107:8' },
  { text: 'Tu palabra es una lámpara a mis pies.', ref: 'Salmos 119:105' },
  { text: 'Lámpara es a mis pies tu palabra.', ref: 'Salmos 119:105' },
  { text: 'Tu palabra es la verdad desde el principio.', ref: 'Salmos 119:160' },
  { text: 'Grande paz tienen los que aman tu ley.', ref: 'Salmos 119:165' },
  { text: 'Mi ayuda viene de Jehová.', ref: 'Salmos 121:2' },
  { text: 'El sol no te fatigará de día ni la luna de noche.', ref: 'Salmos 121:6' },
  { text: 'Jehová guardará tu salida y tu entrada.', ref: 'Salmos 121:8' },
  { text: 'Yo me alegré con los que me decían: a la casa de Jehová iremos.', ref: 'Salmos 122:1' },
  { text: 'Nuestro socorro está en el nombre de Jehová.', ref: 'Salmos 124:8' },
  { text: 'Los que siembran con lágrimas, con regocijo segarán.', ref: 'Salmos 126:5' },
  { text: 'Si Jehová no edificare la casa, en vano trabajan los que la edifican.', ref: 'Salmos 127:1' },
  { text: 'Herencia de Jehová son los hijos.', ref: 'Salmos 127:3' },
  { text: 'Bienaventurado todo aquel que teme a Jehová.', ref: 'Salmos 128:1' },
  { text: 'Muchas veces me han angustiado desde mi juventud.', ref: 'Salmos 129:1' },
  { text: 'Jehová es justo; él cortó las cuerdas de los impíos.', ref: 'Salmos 129:4' },
  { text: 'Jehová guarda a los sencillos.', ref: 'Salmos 116:6' },
  { text: 'Caminaré delante de Jehová en la tierra de los vivientes.', ref: 'Salmos 116:9' },
  { text: 'A Jehová invoqué en mi angustia.', ref: 'Salmos 118:5' },
  { text: 'Jehová está conmigo; no temeré.', ref: 'Salmos 118:6' },
  { text: 'Mejor es confiar en Jehová que confiar en el hombre.', ref: 'Salmos 118:8' },
  { text: 'Fuerte es Jehová; su misericordia es eterna.', ref: 'Salmos 118:29' },
  { text: 'Bienaventurados los perfectos de camino.', ref: 'Salmos 119:1' },
  { text: 'En mi corazón he guardado tus dichos.', ref: 'Salmos 119:11' },
  { text: 'Alegrémonos y regocijémonos y démosle gloria.', ref: 'Apocalipsis 19:7' },
  { text: 'He aquí yo vengo pronto.', ref: 'Apocalipsis 22:12' },
  { text: 'El que tiene sed, venga.', ref: 'Apocalipsis 22:17' },
  { text: 'La gracia del Señor Jesús sea con todos.', ref: 'Apocalipsis 22:21' },
  { text: 'Al que venciere, le daré de comer del árbol de la vida.', ref: 'Apocalipsis 2:7' },
  { text: 'Sé fiel hasta la muerte, y yo te daré la corona de la vida.', ref: 'Apocalipsis 2:10' },
  { text: 'He aquí, yo estoy a la puerta y llamo.', ref: 'Apocalipsis 3:20' },
  { text: 'No entrará en ella ninguna cosa inmunda.', ref: 'Apocalipsis 21:27' },
  { text: 'Dios enjugará toda lágrima de los ojos de ellos.', ref: 'Apocalipsis 21:4' },
  { text: 'He aquí, yo hago nuevas todas las cosas.', ref: 'Apocalipsis 21:5' },
  { text: 'Yo soy el Alfa y la Omega.', ref: 'Apocalipsis 22:13' },
  { text: 'Volveos a mí, dice Jehová de los ejércitos.', ref: 'Zacarías 1:3' },
  { text: 'No por fuerza ni por poder, sino por mi Espíritu.', ref: 'Zacarías 4:6' },
  { text: 'Jehová tu Dios está en medio de ti, poderoso para salvar.', ref: 'Sofonías 3:17' },
  { text: 'El justo por su fe vivirá.', ref: 'Habacuc 2:4' },
  { text: 'Jehová está en su santo templo; calle delante de él toda la tierra.', ref: 'Habacuc 2:20' },
  { text: 'Aun así yo me alegraré en Jehová.', ref: 'Habacuc 3:18' },
  { text: 'Buscad a Jehová, y vivid.', ref: 'Amós 5:6' },
  { text: 'Corra el juicio como las aguas.', ref: 'Amós 5:24' },
  { text: '¿Qué pide Jehová de ti? Hacer justicia, amar misericordia y humillarte.', ref: 'Miqueas 6:8' },
  { text: 'Jehová es bueno, fortaleza en el día de la angustia.', ref: 'Nahúm 1:7' },
  { text: 'Jehová Dios es sol y escudo.', ref: 'Salmos 84:11' },
  { text: 'Cuán amables son tus moradas, oh Jehová.', ref: 'Salmos 84:1' },
  { text: 'Alma mía, espera en Dios.', ref: 'Salmos 42:5' },
  { text: 'De día mandará Jehová su misericordia.', ref: 'Salmos 42:8' },
  { text: 'Envía tu luz y tu verdad.', ref: 'Salmos 43:3' },
  { text: 'Dios es nuestro amparo y fortaleza.', ref: 'Salmos 46:1' },
  { text: 'Hay un río cuyas corrientes alegran la ciudad de Dios.', ref: 'Salmos 46:4' },
  { text: 'Dios está en medio de ella; no será conmovida.', ref: 'Salmos 46:5' },
  { text: 'Jehová de los ejércitos está con nosotros.', ref: 'Salmos 46:7' },
  { text: 'Grande es Jehová en Sión.', ref: 'Salmos 99:2' },
  { text: 'Exaltad a Jehová nuestro Dios.', ref: 'Salmos 99:5' },
  { text: 'Jehová reinará eternamente.', ref: 'Éxodo 15:18' },
  { text: 'Yo soy el que soy.', ref: 'Éxodo 3:14' },
  { text: 'Jehová peleará por vosotros.', ref: 'Éxodo 14:14' },
  { text: 'Honra a tu padre y a tu madre.', ref: 'Éxodo 20:12' },
  { text: 'Amarás a Jehová tu Dios de todo tu corazón.', ref: 'Deuteronomio 6:5' },
  { text: 'Estas palabras que yo te mando estarán sobre tu corazón.', ref: 'Deuteronomio 6:6' },
  { text: 'No solo de pan vivirá el hombre.', ref: 'Deuteronomio 8:3' },
  { text: 'A Jehová tu Dios temerás y a él servirás.', ref: 'Deuteronomio 10:20' },
  { text: 'Porque el Señor tu Dios te ha bendecido en toda obra de tus manos.', ref: 'Deuteronomio 14:29' },
  { text: 'La vida y el bien, la muerte y el mal puso delante de ti.', ref: 'Deuteronomio 30:15' },
  { text: 'Escoge, pues, la vida.', ref: 'Deuteronomio 30:19' },
  { text: 'Nunca se apartará de tu boca este libro de la ley.', ref: 'Josué 1:8' },
  { text: 'Jehová tu Dios estará contigo dondequiera que vayas.', ref: 'Josué 1:9' },
  { text: 'Escogeos hoy a quién sirváis.', ref: 'Josué 24:15' },
  { text: 'Jehová está con vosotros.', ref: 'Jueces 6:12' },
  { text: 'Yo te libraré con mano poderosa.', ref: 'Jueces 7:7' },
  { text: 'Dios es juez justo.', ref: 'Salmos 7:11' },
  { text: 'A ti, oh Jehová, clamaré.', ref: 'Salmos 141:1' },
  { text: 'Suba mi oración como el incienso delante de ti.', ref: 'Salmos 141:2' },
  { text: 'Pon guarda a mi boca, oh Jehová.', ref: 'Salmos 141:3' },
  { text: 'Cántico gradual: Elevo mis ojos a ti.', ref: 'Salmos 123:1' },
  { text: 'Ten piedad de nosotros, oh Jehová.', ref: 'Salmos 123:3' },
  { text: 'Si no hubiera estado Jehová por nosotros.', ref: 'Salmos 124:2' },
  { text: 'Nuestra alma escapó cual ave del lazo.', ref: 'Salmos 124:7' },
  { text: 'Los que confían en Jehová son como el monte de Sión.', ref: 'Salmos 125:1' },
  { text: 'Jehová está alrededor de su pueblo.', ref: 'Salmos 125:2' },
  { text: 'Jehová hace grandes cosas con nosotros.', ref: 'Salmos 126:3' },
  { text: 'El que fue sembrado en buena tierra, este oye la palabra y la entiende.', ref: 'Mateo 13:23' },
  { text: 'Venid en pos de mí, y os haré pescadores de hombres.', ref: 'Mateo 4:19' },
  { text: 'Bienaventurados los pobres en espíritu.', ref: 'Mateo 5:3' },
  { text: 'Bienaventurados los que lloran.', ref: 'Mateo 5:4' },
  { text: 'Bienaventurados los que tienen hambre y sed de justicia.', ref: 'Mateo 5:6' },
  { text: 'Bienaventurados los misericordiosos.', ref: 'Mateo 5:7' },
  { text: 'Bienaventurados los de limpio corazón.', ref: 'Mateo 5:8' },
  { text: 'Bienaventurados los pacificadores.', ref: 'Mateo 5:9' },
  { text: 'Bienaventurados sois cuando os insulten por mi causa.', ref: 'Mateo 5:11' },
  { text: 'Vosotros sois la sal de la tierra.', ref: 'Mateo 5:13' },
  { text: 'Sed perfectos como vuestro Padre celestial es perfecto.', ref: 'Mateo 5:48' },
  { text: 'Cuando ores, entra en tu aposento y ora a tu Padre en secreto.', ref: 'Mateo 6:6' },
  { text: 'Vuestro Padre sabe de qué cosas tenéis necesidad.', ref: 'Mateo 6:8' },
  { text: 'Perdónanos nuestras deudas, como también nosotros perdonamos.', ref: 'Mateo 6:12' },
  { text: 'No os hagáis tesoros en la tierra.', ref: 'Mateo 6:19' },
  { text: 'Donde esté tu tesoro, allí estará también tu corazón.', ref: 'Mateo 6:21' },
  { text: 'No podéis servir a Dios y a las riquezas.', ref: 'Mateo 6:24' },
  { text: 'Mirad las aves del cielo; no siembran ni siegan.', ref: 'Mateo 6:26' },
  { text: 'No os afanéis por vuestra vida.', ref: 'Mateo 6:25' },
  { text: 'No juzguéis para que no seáis juzgados.', ref: 'Mateo 7:1' },
  { text: 'Tratad a los demás como queréis que ellos os traten.', ref: 'Mateo 7:12' },
  { text: 'Entrad por la puerta estrecha.', ref: 'Mateo 7:13' },
  { text: 'Por sus frutos los conoceréis.', ref: 'Mateo 7:16' },
  { text: 'No todo el que me dice Señor, Señor, entrará en el reino.', ref: 'Mateo 7:21' },
  { text: 'Cualquiera que oye estas palabras y las hace, es como un hombre prudente.', ref: 'Mateo 7:24' },
  { text: 'Jesús, compadecido, tocó sus ojos y al instante vieron.', ref: 'Mateo 20:34' },
  { text: 'Amarás al Señor tu Dios con todo tu corazón.', ref: 'Mateo 22:37' },
  { text: 'Velad, porque no sabéis en qué día viene vuestro Señor.', ref: 'Mateo 24:42' },
  { text: 'Bien, buen siervo y fiel; sobre poco has sido fiel.', ref: 'Mateo 25:21' },
  { text: 'Id y haced discípulos a todas las naciones.', ref: 'Mateo 28:19' },
  { text: 'El tiempo se ha cumplido, el reino de Dios está cerca.', ref: 'Marcos 1:15' },
  { text: 'El sábado fue hecho por causa del hombre.', ref: 'Marcos 2:27' },
  { text: 'Jesús los tomó en sus brazos y los bendijo.', ref: 'Marcos 10:16' },
  { text: 'Vende lo que tienes y da a los pobres.', ref: 'Marcos 10:21' },
  { text: 'Ten fe en Dios.', ref: 'Marcos 11:22' },
  { text: 'Alabad a Dios, reino de los cielos.', ref: 'Salmos 22:3' },
  { text: 'Mi Dios, mi Dios, ¿por qué me has desamparado?', ref: 'Salmos 22:1' },
  { text: 'Jehová es mi pastor, nada me falta.', ref: 'Salmos 23:1' },
  { text: 'Junto a aguas de reposo me pastorea.', ref: 'Salmos 23:2' },
  { text: 'Aunque ande en valle de sombra de muerte, no temeré mal alguno.', ref: 'Salmos 23:4' },
  { text: 'Ciertamente el bien y la misericordia me seguirán todos los días.', ref: 'Salmos 23:6' },
  { text: 'De Jehová es la tierra y su plenitud.', ref: 'Salmos 24:1' },
  { text: 'Alzad, puertas, vuestras cabezas, y entrará el Rey de gloria.', ref: 'Salmos 24:7' },
  { text: 'A ti, oh Jehová, levantaré mi alma.', ref: 'Salmos 25:1' },
  { text: 'Enséñame tus caminos, oh Jehová.', ref: 'Salmos 25:4' },
  { text: 'Los caminos de Jehová son misericordia y verdad.', ref: 'Salmos 25:10' },
  { text: 'Jehová da sabiduría; de su boca viene el conocimiento.', ref: 'Proverbios 2:6' },
  { text: 'No te olvides de mi ley; guarda mis mandamientos.', ref: 'Proverbios 3:1' },
  { text: 'En todos tus caminos reconócelo.', ref: 'Proverbios 3:6' },
  { text: 'No seas sabio en tu propia opinión.', ref: 'Proverbios 3:7' },
  { text: 'Honra a Jehová con tus bienes.', ref: 'Proverbios 3:9' },
  { text: 'No menosprecies la disciplina de Jehová.', ref: 'Proverbios 3:11' },
  { text: 'Bienaventurado el hombre que halla la sabiduría.', ref: 'Proverbios 3:13' },
  { text: 'Adquiere sabiduría, adquiere inteligencia.', ref: 'Proverbios 4:5' },
  { text: 'El camino de los justos es como la luz de la aurora.', ref: 'Proverbios 4:18' },
  { text: 'Sobre toda cosa guardada, guarda tu corazón.', ref: 'Proverbios 4:23' },
  { text: 'Los pensamientos del justo son rectitud.', ref: 'Proverbios 12:5' },
  { text: 'El que habla verdad declara justicia.', ref: 'Proverbios 12:17' },
  { text: 'Hay camino que al hombre le parece derecho.', ref: 'Proverbios 14:12' },
  { text: 'El que tarda en airarse es grande de entendimiento.', ref: 'Proverbios 14:29' },
  { text: 'La blanda respuesta quita la ira.', ref: 'Proverbios 15:1' },
  { text: 'Mejor es un poco con el temor de Jehová.', ref: 'Proverbios 15:16' },
  { text: 'Encomienda a Jehová tus obras.', ref: 'Proverbios 16:3' },
  { text: 'El corazón del hombre piensa su camino.', ref: 'Proverbios 16:9' },
  { text: 'Antes del quebrantamiento es la soberbia.', ref: 'Proverbios 16:18' },
  { text: 'El que halla esposa halla el bien.', ref: 'Proverbios 18:22' },
  { text: 'La mujer virtuosa es corona de su marido.', ref: 'Proverbios 12:4' },
  { text: 'Toda mujer sabia edifica su casa.', ref: 'Proverbios 14:1' },
  { text: 'El ojo que se burla del padre tendrá cuervos que lo saquen.', ref: 'Proverbios 30:17' },
  { text: 'Sed fuertes y valientes; no temáis.', ref: '2 Crónicas 32:7' },
  { text: 'Con nosotros está Jehová nuestro Dios.', ref: '2 Crónicas 32:8' },
  { text: 'Dad gracias a Jehová, porque su misericordia es eterna.', ref: '2 Crónicas 20:21' },
  { text: 'Buscad a Dios, y animaos.', ref: '1 Crónicas 22:13' },
  { text: 'Jehová escudriña todos los corazones.', ref: '1 Crónicas 28:9' },
  { text: 'Si le buscáis, será hallado.', ref: '1 Crónicas 28:9' },
  { text: 'Engrandeceos en Jehová.', ref: '1 Crónicas 29:11' },
  { text: 'Porque de la tierra salimos, y a la tierra volveremos.', ref: 'Job 1:21' },
  { text: 'Jehová dio, y Jehová quitó; bendito sea el nombre de Jehová.', ref: 'Job 1:21' },
  { text: 'Yo sé que mi Redentor vive.', ref: 'Job 19:25' },
  { text: 'En su mano está el alma de todo viviente.', ref: 'Job 12:10' },
  { text: 'En tu presencia hay plenitud de gozo.', ref: 'Salmos 16:11' },
  { text: 'Tú me mostrarás la senda de la vida.', ref: 'Salmos 16:11' },
  { text: 'Yo te alabaré, porque tu respuesta me salva.', ref: 'Salmos 18:1' },
  { text: 'Jehová vive, y bendita sea mi roca.', ref: 'Salmos 18:46' },
  { text: 'Los cielos cuentan la gloria de Dios.', ref: 'Salmos 19:1' },
  { text: 'La ley de Jehová es perfecta, que convierte el alma.', ref: 'Salmos 19:7' },
  { text: 'Sean gratos los dichos de mi boca y la meditación de mi corazón.', ref: 'Salmos 19:14' },
  { text: 'El que habita al abrigo del Altísimo.', ref: 'Salmos 91:1' },
  { text: 'Con sus plumas te cubrirá.', ref: 'Salmos 91:4' },
  { text: 'No temerás el terror nocturno.', ref: 'Salmos 91:5' },
  { text: 'A sus ángeles mandará acerca de ti.', ref: 'Salmos 91:11' },
  { text: 'Porque en mí ha puesto su amor, yo lo libraré.', ref: 'Salmos 91:14' },
  { text: 'Me invocará, y yo le responderé.', ref: 'Salmos 91:15' },
  { text: 'Bueno es alabarte, oh Jehová.', ref: 'Salmos 92:1' },
  { text: 'El justo florecerá como la palmera.', ref: 'Salmos 92:12' },
  { text: 'Jehová reina; se vistió de majestad.', ref: 'Salmos 93:1' },
  { text: 'Venid, adoremos y postrémonos.', ref: 'Salmos 95:6' },
  { text: 'Cantad a Jehová cántico nuevo.', ref: 'Salmos 96:1' },
  { text: 'Jehová es grande en extremo.', ref: 'Salmos 96:4' },
  { text: 'Jehová reina; regocíjese la tierra.', ref: 'Salmos 97:1' },
  { text: 'Cantad alegres a Jehová toda la tierra.', ref: 'Salmos 98:4' },
  { text: 'La salvación es de Jehová.', ref: 'Jonás 2:9' },
  { text: 'Dios es un refugio para los pobres.', ref: 'Isaías 25:4' },
  { text: 'Tú guardarás en completa paz a aquel cuyo pensamiento en ti persevera.', ref: 'Isaías 26:3' },
  { text: 'Mi pueblo habitará en morada de paz.', ref: 'Isaías 32:18' },
  { text: 'No temas, porque yo te redimí.', ref: 'Isaías 43:1' },
  { text: 'Porque yo soy Jehová tu Dios.', ref: 'Isaías 43:3' },
  { text: 'Desde el principio no anuncié yo el final.', ref: 'Isaías 46:10' },
  { text: 'Vosotros sois mis testigos, dice Jehová.', ref: 'Isaías 43:10' },
  { text: 'Yo, yo soy el que borro tus rebeliones.', ref: 'Isaías 43:25' },
  { text: 'Derramaré agua sobre el sequedal.', ref: 'Isaías 44:3' },
  { text: 'Yo soy el primero y yo soy el último.', ref: 'Isaías 44:6' },
  { text: 'Mi brazo traerá salvación a las naciones.', ref: 'Isaías 51:5' },
  { text: 'Como los cielos son más altos que la tierra, son mis caminos.', ref: 'Isaías 55:9' },
  { text: 'Mi palabra no volverá a mí vacía.', ref: 'Isaías 55:11' },
  { text: 'El Espíritu del Señor está sobre mí.', ref: 'Isaías 61:1' },
  { text: 'Te desposaré conmigo para siempre.', ref: 'Oseas 2:19' },
  { text: 'Venid y volvamos a Jehová.', ref: 'Oseas 6:1' },
  { text: 'Tu misericordia es mejor que la vida.', ref: 'Salmos 63:3' },
  { text: 'Así te bendeciré en mi vida.', ref: 'Salmos 63:4' },
  { text: 'A Dios el Señor pertenecen las salidas de la muerte.', ref: 'Salmos 68:20' },
  { text: 'Bendito sea el Señor; cada día nos colma de beneficios.', ref: 'Salmos 68:19' },
  { text: 'Cantad a Dios, reinos de la tierra.', ref: 'Salmos 68:32' },
  { text: 'Sálvame, oh Dios, porque las aguas han entrado hasta el alma.', ref: 'Salmos 69:1' },
  { text: 'Dios de Israel, tú eres mi esperanza.', ref: 'Salmos 71:5' },
  { text: 'Seré lleno de tu alabanza cada día.', ref: 'Salmos 71:8' },
  { text: 'Justicia y juicio son el cimiento de tu trono.', ref: 'Salmos 89:14' },
  { text: 'Bienaventurado el pueblo que sabe aclamarte.', ref: 'Salmos 89:15' },
  { text: 'Enséñanos a contar nuestros días.', ref: 'Salmos 90:12' },
  { text: 'Sea la hermosura de Jehová nuestro Dios sobre nosotros.', ref: 'Salmos 90:17' },
  { text: 'El que puso su habitación en los cielos se reirá.', ref: 'Salmos 2:4' },
  { text: 'Besad al Hijo para que no se enoje.', ref: 'Salmos 2:12' },
  { text: 'Respuesta de lengua suave: calma la ira.', ref: 'Proverbios 15:1' },
  { text: 'Reino de Dios no es comida ni bebida.', ref: 'Romanos 14:17' },
  { text: 'Dios da crecimiento a la planta.', ref: '1 Corintios 3:7' },
  { text: 'Glorificad a Dios en vuestro cuerpo.', ref: '1 Corintios 6:20' },
  { text: 'No me avergüenzo del evangelio.', ref: 'Romanos 1:16' },
  { text: 'La palabra de Dios no está encadenada.', ref: '2 Timoteo 2:9' },
  { text: 'Toda Escritura es inspirada por Dios.', ref: '2 Timoteo 3:16' },
  { text: 'Predica la palabra; a tiempo y fuera de tiempo.', ref: '2 Timoteo 4:2' },
  { text: 'Dios no nos ha dado un espíritu de cobardía.', ref: '2 Timoteo 1:7' },
  { text: 'Pelea la buena batalla de la fe.', ref: '1 Timoteo 6:12' },
  { text: 'Grande es el misterio de la piedad.', ref: '1 Timoteo 3:16' },
  { text: 'Por nada estéis afanosos, sino orad.', ref: 'Filipenses 4:6' },
  { text: 'Cristo Jesús vino al mundo para salvar a los pecadores.', ref: '1 Timoteo 1:15' },
  { text: 'La piedad con contentamiento es gran ganancia.', ref: '1 Timoteo 6:6' },
  { text: 'Sed santos en toda vuestra manera de vivir.', ref: '1 Pedro 1:15' },
  { text: 'Creced en la gracia y el conocimiento de nuestro Señor.', ref: '2 Pedro 3:18' },
  { text: 'Andemos en la luz, como él está en la luz.', ref: '1 Juan 1:7' },
  { text: 'Mirad qué amor nos ha dado el Padre.', ref: '1 Juan 3:1' },
  { text: 'Hijitos, amémonos de palabra y de obra.', ref: '1 Juan 3:18' },
  { text: 'Dios es amor; el que permanece en amor permanece en Dios.', ref: '1 Juan 4:16' },
  { text: 'El que teme no ha sido perfeccionado en el amor.', ref: '1 Juan 4:18' },
  { text: 'El que cree en el Hijo tiene vida eterna.', ref: '1 Juan 5:13' },
  { text: 'Sed sobrios y velad en oración.', ref: '1 Pedro 4:7' },
  { text: 'Someteos a toda institución humana por amor del Señor.', ref: '1 Pedro 2:13' },
  { text: 'El fin de todas las cosas se acerca.', ref: '1 Pedro 4:7' },
  { text: 'Dad gracias en todo.', ref: '1 Tesalonicenses 5:18' },
  { text: 'Orad sin cesar.', ref: '1 Tesalonicenses 5:17' },
  { text: 'No apaguéis al Espíritu.', ref: '1 Tesalonicenses 5:19' },
  { text: 'Examinadlo todo; retened lo bueno.', ref: '1 Tesalonicenses 5:21' },
  { text: 'La paz sea con vosotros.', ref: '2 Tesalonicenses 3:16' },
  { text: 'Sed pacientes hasta la venida del Señor.', ref: 'Santiago 5:7' },
  { text: 'El que sabe hacer lo bueno y no lo hace, comete pecado.', ref: 'Santiago 4:17' },
  { text: 'Toda buena dádiva y todo don perfecto desciende del Padre.', ref: 'Santiago 1:17' },
  { text: 'Todos ofendemos muchas veces.', ref: 'Santiago 3:2' },
  { text: 'Humillaos en la presencia del Señor.', ref: 'Santiago 4:10' },
  { text: 'Hermanos míos, no os quejéis unos contra otros.', ref: 'Santiago 5:9' },
  { text: 'Sea vuestro sí, sí; y vuestro no, no.', ref: 'Santiago 5:12' },
  { text: 'Perseverad en la oración.', ref: 'Colosenses 4:2' },
  { text: 'Cristo es la cabeza del cuerpo que es la iglesia.', ref: 'Colosenses 1:18' },
  { text: 'Todo lo que hagáis, hacedlo de corazón, como para el Señor.', ref: 'Colosenses 3:23' },
  { text: 'Vestíos de compasión, bondad, humildad, mansedumbre y paciencia.', ref: 'Colosenses 3:12' },
  { text: 'Sobre todas estas cosas vestíos de amor.', ref: 'Colosenses 3:14' },
  { text: 'La paz de Cristo gobierne en vuestros corazones.', ref: 'Colosenses 3:15' },
  { text: 'Palabra de Cristo more en abundancia en vosotros.', ref: 'Colosenses 3:16' },
  { text: 'Cristo en vosotros, la esperanza de gloria.', ref: 'Colosenses 1:27' },
  { text: 'Por fe andamos, no por vista.', ref: '2 Corintios 5:7' },
  { text: 'Vosotros sois carta de Cristo.', ref: '2 Corintios 3:3' },
  { text: 'Todo es posible para el que cree.', ref: 'Marcos 9:23' },
  { text: 'Jesús le dijo: Ve, tu fe te ha salvado.', ref: 'Marcos 10:52' },
  { text: 'El que cree y es bautizado será salvo.', ref: 'Marcos 16:16' },
  { text: 'A Dios nadie le vio jamás; el unigénito Hijo le ha dado a conocer.', ref: 'Juan 1:18' },
  { text: 'El que no ama no ha conocido a Dios.', ref: '1 Juan 4:8' },
  { text: 'Temed a Dios y dadle gloria.', ref: 'Apocalipsis 14:7' },
  { text: 'Justos son tus juicios.', ref: 'Apocalipsis 16:7' },
  { text: 'He aquí, vengo pronto. Bienaventurado el que guarda las palabras de esta profecía.', ref: 'Apocalipsis 22:7' },
];

function getDayOfYear() {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now - start;
  const oneDay = 86400000;
  return Math.floor(diff / oneDay);
}

export default function DailyVerse() {
  const dayOfYear = getDayOfYear();
  const verse = VERSES[(dayOfYear - 1) % VERSES.length];

  return (
    <div className="mx-auto w-full px-4 pt-6 pb-2 max-w-3xl">
      <div className="relative bg-white rounded-2xl border border-gold/20 shadow-sm overflow-hidden">
        <div className="absolute left-0 top-0 bottom-0 w-1 bg-gradient-to-b from-gold to-amber-300" />
        <div className="pl-5 pr-6 py-4">
          <div className="flex items-start gap-3">
            <span className="text-gold shrink-0 mt-0.5 text-lg">📖</span>
            <div className="min-w-0">
              <p className="text-xs uppercase tracking-wider text-gold font-semibold mb-1">
                Versículo del día
              </p>
              <p className="text-sm italic leading-relaxed text-dark-blue/85 font-serif">
                &ldquo;{verse.text}&rdquo;
              </p>
              <p className="text-xs text-dark-blue/50 mt-1.5 font-medium">
                — {verse.ref}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}