const quotes = [
  // ── JESÚS (25) ──
  { quote: 'Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.', options: ['Jesús', 'Pablo', 'Pedro', 'Juan'], correct: 'Jesús', reference: 'Juan 14:6', passage: 'Jesús le dijo: Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.' },
  { quote: 'Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.', options: ['Jesús', 'Moisés', 'David', 'Isaías'], correct: 'Jesús', reference: 'Mateo 11:28', passage: 'Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.' },
  { quote: 'Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.', options: ['Jesús', 'Salomón', 'Pablo', 'Pedro'], correct: 'Jesús', reference: 'Mateo 6:33', passage: 'Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.' },
  { quote: 'Yo soy la resurrección y la vida; el que cree en mí, aunque esté muerto, vivirá.', options: ['Jesús', 'Marta', 'Pablo', 'Lázaro'], correct: 'Jesús', reference: 'Juan 11:25', passage: 'Le dijo Jesús: Yo soy la resurrección y la vida; el que cree en mí, aunque esté muerto, vivirá.' },
  { quote: 'Yo soy el pan de vida; el que a mí viene, nunca tendrá hambre.', options: ['Jesús', 'Moisés', 'David', 'Elías'], correct: 'Jesús', reference: 'Juan 6:35', passage: 'Jesús les dijo: Yo soy el pan de vida; el que a mí viene, nunca tendrá hambre.' },
  { quote: 'Amad a vuestros enemigos, bendecid a los que os maldicen, haced bien a los que os aborrecen.', options: ['Jesús', 'Pablo', 'Pedro', 'Salomón'], correct: 'Jesús', reference: 'Mateo 5:44', passage: 'Pero yo os digo: Amad a vuestros enemigos, bendecid a los que os maldicen, haced bien a los que os aborrecen.' },
  { quote: 'No solo de pan vivirá el hombre, sino de toda palabra que sale de la boca de Dios.', options: ['Jesús', 'Moisés', 'Pablo', 'David'], correct: 'Jesús', reference: 'Mateo 4:4', passage: 'Él respondiendo, dijo: Escrito está: No solo de pan vivirá el hombre, sino de toda palabra que sale de la boca de Dios.' },
  { quote: 'Apacienta mis ovejas.', options: ['Jesús', 'Pedro', 'Pablo', 'Juan'], correct: 'Jesús', reference: 'Juan 21:17', passage: 'Le dijo: Apacienta mis ovejas.' },
  { quote: 'He aquí yo estoy con vosotros todos los días, hasta el fin del mundo.', options: ['Jesús', 'Pablo', 'Pedro', 'Mateo'], correct: 'Jesús', reference: 'Mateo 28:20', passage: 'Y he aquí yo estoy con vosotros todos los días, hasta el fin del mundo.' },
  { quote: 'Dejad a los niños venir a mí, y no se lo impidáis; porque de los tales es el reino de Dios.', options: ['Jesús', 'Pedro', 'Santiago', 'Juan'], correct: 'Jesús', reference: 'Marcos 10:14', passage: 'Dejad a los niños venir a mí, y no se lo impidáis; porque de los tales es el reino de Dios.' },
  { quote: 'El que de vosotros esté sin pecado, sea el primero en arrojar la piedra.', options: ['Jesús', 'Moisés', 'Pablo', 'Pedro'], correct: 'Jesús', reference: 'Juan 8:7', passage: 'Y como insistieran en preguntarle, se enderezó y les dijo: El que de vosotros esté sin pecado, sea el primero en arrojar la piedra.' },
  { quote: 'En la casa de mi Padre muchas moradas hay; voy, pues, a preparar lugar para vosotros.', options: ['Jesús', 'Pablo', 'Pedro', 'Esteban'], correct: 'Jesús', reference: 'Juan 14:2', passage: 'En la casa de mi Padre muchas moradas hay; si no fuera así, yo os lo hubiera dicho; voy, pues, a preparar lugar para vosotros.' },
  { quote: 'Padre, perdónalos, porque no saben lo que hacen.', options: ['Jesús', 'Esteban', 'Pablo', 'Pedro'], correct: 'Jesús', reference: 'Lucas 23:34', passage: 'Y Jesús decía: Padre, perdónalos, porque no saben lo que hacen.' },
  { quote: 'Dios mío, Dios mío, ¿por qué me has desamparado?', options: ['Jesús', 'David', 'Job', 'Jeremías'], correct: 'Jesús', reference: 'Mateo 27:46', passage: 'Cerca de la hora novena, Jesús clamó a gran voz, diciendo: Elí, Elí, ¿lama sabactani? Esto es: Dios mío, Dios mío, ¿por qué me has desamparado?' },
  { quote: 'Consumado es.', options: ['Jesús', 'Pablo', 'Juan', 'Pedro'], correct: 'Jesús', reference: 'Juan 19:30', passage: 'Cuando Jesús hubo tomado el vinagre, dijo: Consumado es. Y habiendo inclinado la cabeza, entregó el espíritu.' },
  { quote: 'Yo soy la luz del mundo; el que me sigue, no andará en tinieblas.', options: ['Jesús', 'David', 'Isaías', 'Pablo'], correct: 'Jesús', reference: 'Juan 8:12', passage: 'Otra vez Jesús les habló, diciendo: Yo soy la luz del mundo; el que me sigue, no andará en tinieblas, sino que tendrá la luz de la vida.' },
  { quote: 'No se turbe vuestro corazón; creéis en Dios, creed también en mí.', options: ['Jesús', 'Pablo', 'Pedro', 'Juan'], correct: 'Jesús', reference: 'Juan 14:1', passage: 'No se turbe vuestro corazón; creéis en Dios, creed también en mí.' },
  { quote: 'Bienaventurados los pobres en espíritu, porque de ellos es el reino de los cielos.', options: ['Jesús', 'David', 'Salomón', 'Pablo'], correct: 'Jesús', reference: 'Mateo 5:3', passage: 'Bienaventurados los pobres en espíritu, porque de ellos es el reino de los cielos.' },
  { quote: 'Vosotros sois la luz del mundo; una ciudad asentada sobre un monte no se puede esconder.', options: ['Jesús', 'Pablo', 'Pedro', 'Salomón'], correct: 'Jesús', reference: 'Mateo 5:14', passage: 'Vosotros sois la luz del mundo; una ciudad asentada sobre un monte no se puede esconder.' },
  { quote: 'No juzguéis, para que no seáis juzgados.', options: ['Jesús', 'Pablo', 'Salomón', 'Santiago'], correct: 'Jesús', reference: 'Mateo 7:1', passage: 'No juzguéis, para que no seáis juzgados.' },
  { quote: 'Por sus frutos los conoceréis.', options: ['Jesús', 'Pablo', 'Pedro', 'Juan'], correct: 'Jesús', reference: 'Mateo 7:16', passage: 'Por sus frutos los conoceréis. ¿Acaso se recogen uvas de los espinos, o higos de los abrojos?' },
  { quote: 'Y conoceréis la verdad, y la verdad os hará libres.', options: ['Jesús', 'Pablo', 'Juan', 'Pedro'], correct: 'Jesús', reference: 'Juan 8:32', passage: 'Y conoceréis la verdad, y la verdad os hará libres.' },
  { quote: 'Ninguno puede servir a dos señores; porque o aborrecerá al uno y amará al otro.', options: ['Jesús', 'Pablo', 'Salomón', 'Josué'], correct: 'Jesús', reference: 'Mateo 6:24', passage: 'Ninguno puede servir a dos señores; porque o aborrecerá al uno y amará al otro.' },
  { quote: 'No he venido para llamar a justos, sino a pecadores, al arrepentimiento.', options: ['Jesús', 'Pablo', 'Pedro', 'Mateo'], correct: 'Jesús', reference: 'Lucas 5:32', passage: 'No he venido para llamar a justos, sino a pecadores, al arrepentimiento.' },
  { quote: 'El que quiera ser el primero, será el último de todos y el servidor de todos.', options: ['Jesús', 'Pablo', 'Pedro', 'Santiago'], correct: 'Jesús', reference: 'Marcos 9:35', passage: 'Entonces él se sentó y llamó a los doce, y les dijo: Si alguno quiere ser el primero, será el último de todos y el servidor de todos.' },

  // ── PABLO (15) ──
  { quote: 'Todo lo puedo en Cristo que me fortalece.', options: ['Pablo', 'Pedro', 'Juan', 'Santiago'], correct: 'Pablo', reference: 'Filipenses 4:13', passage: 'Todo lo puedo en Cristo que me fortalece.' },
  { quote: 'Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien.', options: ['Pablo', 'Pedro', 'Juan', 'David'], correct: 'Pablo', reference: 'Romanos 8:28', passage: 'Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien, esto es, a los que conforme a su propósito son llamados.' },
  { quote: 'Por cuanto todos pecaron, y están destituidos de la gloria de Dios.', options: ['Pablo', 'David', 'Salomón', 'Isaías'], correct: 'Pablo', reference: 'Romanos 3:23', passage: 'Por cuanto todos pecaron, y están destituidos de la gloria de Dios.' },
  { quote: 'Si confesares con tu boca al Señor Jesús, y creyeres en tu corazón que Dios le levantó de los muertos, serás salvo.', options: ['Pablo', 'Pedro', 'Juan', 'Jesús'], correct: 'Pablo', reference: 'Romanos 10:9', passage: 'Si confesares con tu boca al Señor Jesús, y creyeres en tu corazón que Dios le levantó de los muertos, serás salvo.' },
  { quote: 'El amor es sufrido, es benigno; el amor no tiene envidia, el amor no es jactancioso, no se envanece.', options: ['Pablo', 'Pedro', 'Juan', 'Salomón'], correct: 'Pablo', reference: '1 Corintios 13:4', passage: 'El amor es sufrido, es benigno; el amor no tiene envidia, el amor no es jactancioso, no se envanece.' },
  { quote: 'Y ahora permanecen la fe, la esperanza y el amor, estos tres; pero el mayor de ellos es el amor.', options: ['Pablo', 'Pedro', 'Juan', 'Santiago'], correct: 'Pablo', reference: '1 Corintios 13:13', passage: 'Y ahora permanecen la fe, la esperanza y el amor, estos tres; pero el mayor de ellos es el amor.' },
  { quote: 'No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento.', options: ['Pablo', 'Pedro', 'Juan', 'Santiago'], correct: 'Pablo', reference: 'Romanos 12:2', passage: 'No os conforméis a este siglo, sino transformaos por medio de la renovación de vuestro entendimiento.' },
  { quote: 'La paga del pecado es muerte, mas la dádiva de Dios es vida eterna en Cristo Jesús Señor nuestro.', options: ['Pablo', 'Pedro', 'Juan', 'David'], correct: 'Pablo', reference: 'Romanos 6:23', passage: 'Porque la paga del pecado es muerte, mas la dádiva de Dios es vida eterna en Cristo Jesús Señor nuestro.' },
  { quote: 'A los que aman a Dios, todas las cosas les ayudan a bien.', options: ['Pablo', 'Pedro', 'Juan', 'David'], correct: 'Pablo', reference: 'Romanos 8:28', passage: 'Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien.' },
  { quote: 'Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios.', options: ['Pablo', 'Pedro', 'Juan', 'Santiago'], correct: 'Pablo', reference: 'Efesios 2:8', passage: 'Porque por gracia sois salvos por medio de la fe; y esto no de vosotros, pues es don de Dios.' },
  { quote: 'He peleado la buena batalla, he acabado la carrera, he guardado la fe.', options: ['Pablo', 'Pedro', 'Juan', 'Timoteo'], correct: 'Pablo', reference: '2 Timoteo 4:7', passage: 'He peleado la buena batalla, he acabado la carrera, he guardado la fe.' },
  { quote: 'Vestíos de toda la armadura de Dios, para que podáis estar firmes contra las asechanzas del diablo.', options: ['Pablo', 'Pedro', 'Juan', 'Josué'], correct: 'Pablo', reference: 'Efesios 6:11', passage: 'Vestíos de toda la armadura de Dios, para que podáis estar firmes contra las asechanzas del diablo.' },
  { quote: 'El Señor es el Espíritu; y donde está el Espíritu del Señor, allí hay libertad.', options: ['Pablo', 'Pedro', 'Juan', 'Moisés'], correct: 'Pablo', reference: '2 Corintios 3:17', passage: 'Porque el Señor es el Espíritu; y donde está el Espíritu del Señor, allí hay libertad.' },
  { quote: 'Todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres.', options: ['Pablo', 'Pedro', 'Juan', 'Salomón'], correct: 'Pablo', reference: 'Colosenses 3:23', passage: 'Y todo lo que hagáis, hacedlo de corazón, como para el Señor y no para los hombres.' },
  { quote: 'He sido crucificado con Cristo, y ya no vivo yo, mas vive Cristo en mí.', options: ['Pablo', 'Pedro', 'Juan', 'Santiago'], correct: 'Pablo', reference: 'Gálatas 2:20', passage: 'Con Cristo estoy juntamente crucificado, y ya no vivo yo, mas vive Cristo en mí.' },

  // ── DAVID (10) ──
  { quote: 'Jehová es mi pastor; nada me faltará.', options: ['David', 'Salomón', 'Moisés', 'Asaf'], correct: 'David', reference: 'Salmo 23:1', passage: 'Jehová es mi pastor; nada me faltará.' },
  { quote: 'Lámpara es a mis pies tu palabra, y lumbrera a mi camino.', options: ['David', 'Salomón', 'Moisés', 'Isaías'], correct: 'David', reference: 'Salmo 119:105', passage: 'Lámpara es a mis pies tu palabra, y lumbrera a mi camino.' },
  { quote: 'Alzaré mis ojos a los montes; ¿de dónde vendrá mi socorro?', options: ['David', 'Salomón', 'Moisés', 'Isaías'], correct: 'David', reference: 'Salmo 121:1', passage: 'Alzaré mis ojos a los montes; ¿de dónde vendrá mi socorro?' },
  { quote: 'Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.', options: ['David', 'Salomón', 'Moisés', 'Josué'], correct: 'David', reference: 'Salmo 46:1', passage: 'Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.' },
  { quote: 'Los cielos cuentan la gloria de Dios, y el firmamento anuncia la obra de sus manos.', options: ['David', 'Salomón', 'Moisés', 'Job'], correct: 'David', reference: 'Salmo 19:1', passage: 'Los cielos cuentan la gloria de Dios, y el firmamento anuncia la obra de sus manos.' },
  { quote: 'Examíname, oh Dios, y conoce mi corazón; pruébame y conoce mis pensamientos.', options: ['David', 'Salomón', 'Moisés', 'Jeremías'], correct: 'David', reference: 'Salmo 139:23', passage: 'Examíname, oh Dios, y conoce mi corazón; pruébame y conoce mis pensamientos.' },
  { quote: 'Crea en mí, oh Dios, un corazón limpio, y renueva un espíritu recto dentro de mí.', options: ['David', 'Salomón', 'Moisés', 'Isaías'], correct: 'David', reference: 'Salmo 51:10', passage: 'Crea en mí, oh Dios, un corazón limpio, y renueva un espíritu recto dentro de mí.' },
  { quote: 'Tú eres mi refugio y mi escudo; en tu palabra he esperado.', options: ['David', 'Salomón', 'Moisés', 'Josué'], correct: 'David', reference: 'Salmo 119:114', passage: 'Tú eres mi refugio y mi escudo; en tu palabra he esperado.' },
  { quote: 'El Señor es mi luz y mi salvación; ¿de quién temeré?', options: ['David', 'Salomón', 'Moisés', 'Isaías'], correct: 'David', reference: 'Salmo 27:1', passage: 'Jehová es mi luz y mi salvación; ¿de quién temeré?' },
  { quote: 'Gustad y ved que es bueno Jehová; dichoso el hombre que confía en él.', options: ['David', 'Salomón', 'Moisés', 'Job'], correct: 'David', reference: 'Salmo 34:8', passage: 'Gustad y ved que es bueno Jehová; dichoso el hombre que confía en él.' },

  // ── MOISÉS (8) ──
  { quote: 'Escucha, oh Israel: Jehová nuestro Dios, Jehová uno es.', options: ['Moisés', 'David', 'Josué', 'Samuel'], correct: 'Moisés', reference: 'Deuteronomio 6:4', passage: 'Escucha, oh Israel: Jehová nuestro Dios, Jehová uno es.' },
  { quote: 'Escoge, pues, la vida, para que vivas tú y tu descendencia.', options: ['Moisés', 'David', 'Josué', 'Salomón'], correct: 'Moisés', reference: 'Deuteronomio 30:19', passage: 'Escoge, pues, la vida, para que vivas tú y tu descendencia.' },
  { quote: 'No temas; estad firmes, y ved la salvación de Jehová que él hará hoy con vosotros.', options: ['Moisés', 'David', 'Josué', 'Samuel'], correct: 'Moisés', reference: 'Éxodo 14:13', passage: 'No temáis; estad firmes, y ved la salvación de Jehová que él hará hoy con vosotros.' },
  { quote: '¿Quién soy yo para ir a Faraón y sacar de Egipto a los hijos de Israel?', options: ['Moisés', 'Aarón', 'Josué', 'David'], correct: 'Moisés', reference: 'Éxodo 3:11', passage: 'Entonces Moisés respondió a Dios: ¿Quién soy yo para ir a Faraón y sacar de Egipto a los hijos de Israel?' },
  { quote: 'Te ruego que me muestres tu gloria.', options: ['Moisés', 'David', 'Elías', 'Isaías'], correct: 'Moisés', reference: 'Éxodo 33:18', passage: 'Él dijo entonces: Te ruego que me muestres tu gloria.' },
  { quote: 'El hombre no solo de pan vivirá, sino de todo lo que sale de la boca de Jehová.', options: ['Moisés', 'David', 'Jesús', 'Pablo'], correct: 'Moisés', reference: 'Deuteronomio 8:3', passage: 'El hombre no solo de pan vivirá, sino de todo lo que sale de la boca de Jehová.' },
  { quote: 'El eterno Dios es tu refugio, y acá abajo los brazos eternos.', options: ['Moisés', 'David', 'Josué', 'Isaías'], correct: 'Moisés', reference: 'Deuteronomio 33:27', passage: 'El eterno Dios es tu refugio, y acá abajo los brazos eternos.' },
  { quote: 'Oye, Israel, tú vas hoy a pasar el Jordán, para entrar a poseer naciones más numerosas que tú.', options: ['Moisés', 'Josué', 'David', 'Samuel'], correct: 'Moisés', reference: 'Deuteronomio 9:1', passage: 'Oye, Israel: tú vas hoy a pasar el Jordán, para entrar a poseer naciones más numerosas y más poderosas que tú.' },

  // ── SALOMÓN (7) ──
  { quote: 'Fíate de Jehová de todo tu corazón, y no te apoyes en tu propia prudencia.', options: ['Salomón', 'David', 'Moisés', 'Job'], correct: 'Salomón', reference: 'Proverbios 3:5', passage: 'Fíate de Jehová de todo tu corazón, y no te apoyes en tu propia prudencia.' },
  { quote: 'El principio de la sabiduría es el temor de Jehová.', options: ['Salomón', 'David', 'Moisés', 'Job'], correct: 'Salomón', reference: 'Proverbios 9:10', passage: 'El principio de la sabiduría es el temor de Jehová.' },
  { quote: 'Vanidad de vanidades, todo es vanidad.', options: ['Salomón', 'David', 'Moisés', 'Job'], correct: 'Salomón', reference: 'Eclesiastés 1:2', passage: 'Vanidad de vanidades, dijo el Predicador; vanidad de vanidades, todo es vanidad.' },
  { quote: 'Todo tiene su tiempo, y todo lo que se quiere debajo del cielo tiene su hora.', options: ['Salomón', 'David', 'Moisés', 'Job'], correct: 'Salomón', reference: 'Eclesiastés 3:1', passage: 'Todo tiene su tiempo, y todo lo que se quiere debajo del cielo tiene su hora.' },
  { quote: 'El que guarda su boca y su lengua, guarda su alma de angustias.', options: ['Salomón', 'David', 'Moisés', 'Santiago'], correct: 'Salomón', reference: 'Proverbios 21:23', passage: 'El que guarda su boca y su lengua, guarda su alma de angustias.' },
  { quote: 'La bendición de Jehová es la que enriquece, y no añade tristeza con ella.', options: ['Salomón', 'David', 'Moisés', 'Job'], correct: 'Salomón', reference: 'Proverbios 10:22', passage: 'La bendición de Jehová es la que enriquece, y no añade tristeza con ella.' },
  { quote: 'El temor de Jehová es principio de la sabiduría, y el conocimiento del Santísimo es la inteligencia.', options: ['Salomón', 'David', 'Moisés', 'Job'], correct: 'Salomón', reference: 'Proverbios 9:10', passage: 'El temor de Jehová es principio de la sabiduría, y el conocimiento del Santísimo es la inteligencia.' },

  // ── PEDRO (6) ──
  { quote: 'Tú eres el Cristo, el Hijo del Dios viviente.', options: ['Pedro', 'Juan', 'Tomás', 'Mateo'], correct: 'Pedro', reference: 'Mateo 16:16', passage: 'Respondiendo Simón Pedro, dijo: Tú eres el Cristo, el Hijo del Dios viviente.' },
  { quote: 'Señor, ¿a quién iremos? Tú tienes palabras de vida eterna.', options: ['Pedro', 'Juan', 'Tomás', 'Andrés'], correct: 'Pedro', reference: 'Juan 6:68', passage: 'Le respondió Simón Pedro: Señor, ¿a quién iremos? Tú tienes palabras de vida eterna.' },
  { quote: 'No tengo plata ni oro, pero lo que tengo te doy: en el nombre de Jesucristo de Nazaret, levántate y anda.', options: ['Pedro', 'Juan', 'Pablo', 'Esteban'], correct: 'Pedro', reference: 'Hechos 3:6', passage: 'Y Pedro dijo: No tengo plata ni oro, pero lo que tengo te doy: en el nombre de Jesucristo de Nazaret, levántate y anda.' },
  { quote: 'Es necesario obedecer a Dios antes que a los hombres.', options: ['Pedro', 'Juan', 'Pablo', 'Esteban'], correct: 'Pedro', reference: 'Hechos 5:29', passage: 'Respondiendo Pedro y los apóstoles, dijeron: Es necesario obedecer a Dios antes que a los hombres.' },
  { quote: 'Antes bien, estad siempre preparados para presentar defensa con mansedumbre y reverencia.', options: ['Pedro', 'Pablo', 'Juan', 'Santiago'], correct: 'Pedro', reference: '1 Pedro 3:15', passage: 'Estad siempre preparados para presentar defensa con mansedumbre y reverencia ante todo el que os demande razón de la esperanza que hay en vosotros.' },
  { quote: 'Como el Señor perdonó, así también hacedlo vosotros.', options: ['Pedro', 'Pablo', 'Juan', 'Santiago'], correct: 'Pedro', reference: '1 Pedro 4:8', passage: 'Y ante todo, tened entre vosotros ferviente amor; porque el amor cubrirá multitud de pecados.' },

  // ── ISAÍAS (8) ──
  { quote: 'Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas.', options: ['Isaías', 'David', 'Jeremías', 'Ezequiel'], correct: 'Isaías', reference: 'Isaías 40:31', passage: 'Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas; correrán, y no se cansarán; caminarán, y no se fatigarán.' },
  { quote: 'Aquí estoy, envíame a mí.', options: ['Isaías', 'Jeremías', 'Moisés', 'Samuel'], correct: 'Isaías', reference: 'Isaías 6:8', passage: 'Después oí la voz del Señor, que decía: ¿A quién enviaré, y quién irá por nosotros? Entonces respondí yo: Heme aquí, envíame a mí.' },
  { quote: 'Porque nos ha nacido un niño, se nos ha dado un hijo, y el principado sobre su hombro.', options: ['Isaías', 'Miqueas', 'Jeremías', 'David'], correct: 'Isaías', reference: 'Isaías 9:6', passage: 'Porque un niño nos es nacido, hijo nos es dado, y el principado sobre su hombro.' },
  { quote: 'Venid luego, dice Jehová, y estemos a cuenta: si vuestros pecados fueren como la grana, como la nieve serán emblanquecidos.', options: ['Isaías', 'David', 'Jeremías', 'Ezequiel'], correct: 'Isaías', reference: 'Isaías 1:18', passage: 'Venid luego, dice Jehová, y estemos a cuenta: si vuestros pecados fueren como la grana, como la nieve serán emblanquecidos.' },
  { quote: 'No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo.', options: ['Isaías', 'David', 'Jeremías', 'Josué'], correct: 'Isaías', reference: 'Isaías 41:10', passage: 'No temas, porque yo estoy contigo; no desmayes, porque yo soy tu Dios que te esfuerzo; siempre te ayudaré.' },
  { quote: 'Mas él herido fue por nuestras rebeliones, molido por nuestros pecados.', options: ['Isaías', 'David', 'Jeremías', 'Zacarías'], correct: 'Isaías', reference: 'Isaías 53:5', passage: 'Mas él herido fue por nuestras rebeliones, molido por nuestros pecados; el castigo de nuestra paz fue sobre él.' },
  { quote: 'Ciertamente, él llevó nuestras enfermedades y sufrió nuestros dolores.', options: ['Isaías', 'David', 'Jeremías', 'Mateo'], correct: 'Isaías', reference: 'Isaías 53:4', passage: 'Ciertamente llevó él nuestras enfermedades, y sufrió nuestros dolores.' },
  { quote: 'Las vigas de tus puertas serán de rubíes, y tus puertas de piedras preciosas.', options: ['Isaías', 'David', 'Ezequiel', 'Jeremías'], correct: 'Isaías', reference: 'Isaías 54:12', passage: 'Tus ventanas pondré de piedras preciosas, tus puertas de rubíes.' },

  // ── JEREMÍAS (5) ──
  { quote: 'Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal.', options: ['Jeremías', 'Isaías', 'David', 'Ezequiel'], correct: 'Jeremías', reference: 'Jeremías 29:11', passage: 'Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal, para daros el fin que esperáis.' },
  { quote: 'Bendito el varón que confía en Jehová, y cuya confianza es Jehová.', options: ['Jeremías', 'David', 'Isaías', 'Salomón'], correct: 'Jeremías', reference: 'Jeremías 17:7', passage: 'Bendito el varón que confía en Jehová, y cuya confianza es Jehová.' },
  { quote: 'Grande es tu fidelidad.', options: ['Jeremías', 'David', 'Isaías', 'Moisés'], correct: 'Jeremías', reference: 'Lamentaciones 3:23', passage: 'Nuevas son cada mañana; grande es tu fidelidad.' },
  { quote: 'Antes que te formase en el vientre te conocí, y antes que nacieses te santifiqué.', options: ['Jeremías', 'Isaías', 'David', 'Samuel'], correct: 'Jeremías', reference: 'Jeremías 1:5', passage: 'Antes que te formase en el vientre te conocí, y antes que nacieses te santifiqué, te di por profeta a las naciones.' },
  { quote: '¿Acaso alguno se desviará y no volverá?', options: ['Jeremías', 'Isaías', 'Oseas', 'Ezequiel'], correct: 'Jeremías', reference: 'Jeremías 8:4', passage: 'Les dirás: Así ha dicho Jehová: El que cae, ¿no se levanta? El que se desvía, ¿no vuelve?' },

  // ── ABRAHAM (4) ──
  { quote: 'Yo soy polvo y ceniza.', options: ['Abraham', 'Job', 'Moisés', 'David'], correct: 'Abraham', reference: 'Génesis 18:27', passage: 'Y respondió Abraham y dijo: He aquí ahora que he comenzado a hablar a mi Señor, aunque soy polvo y ceniza.' },
  { quote: 'Si te place, pon tu mano debajo de mi muslo, y júrame por Jehová.', options: ['Abraham', 'Isaac', 'Jacob', 'José'], correct: 'Abraham', reference: 'Génesis 24:2', passage: 'Y dijo Abraham a un criado suyo, el más viejo de su casa: Pon tu mano debajo de mi muslo.' },
  { quote: 'En tu simiente serán benditas todas las naciones de la tierra.', options: ['Dios', 'Abraham', 'Isaac', 'Moisés'], correct: 'Dios', reference: 'Génesis 22:18', passage: 'En tu simiente serán benditas todas las naciones de la tierra, por cuanto obedeciste a mi voz.' },
  { quote: 'Cree Abraham a Dios, y le fue contado por justicia.', options: ['Moisés', 'Pablo', 'Santiago', 'David'], correct: 'Pablo', reference: 'Romanos 4:3', passage: 'Porque ¿qué dice la Escritura? Creyó Abraham a Dios, y le fue contado por justicia.' },

  // ── JOSÉ (4) ──
  { quote: 'Vosotros pensasteis mal contra mí, mas Dios lo encaminó a bien.', options: ['José', 'Jacob', 'David', 'Job'], correct: 'José', reference: 'Génesis 50:20', passage: 'Vosotros pensasteis mal contra mí, mas Dios lo encaminó a bien, para hacer lo que vemos hoy, para mantener en vida a mucho pueblo.' },
  { quote: '¿Cómo, pues, haría yo este gran mal y pecaría contra Dios?', options: ['José', 'David', 'Sansón', 'Job'], correct: 'José', reference: 'Génesis 39:9', passage: '¿Cómo, pues, haría yo este gran mal y pecaría contra Dios?' },
  { quote: 'No me ha hecho falta nada mientras he estado contigo.', options: ['José', 'Jacob', 'David', 'Rut'], correct: 'José', reference: 'Génesis 47:25', passage: 'Y ellos respondieron: Nos has dado la vida; hallemos gracia en ojos de mi señor, y seamos siervos de Faraón.' },
  { quote: 'A mí me envió Dios antes que vosotros, para preservaros vida.', options: ['José', 'Moisés', 'David', 'Samuel'], correct: 'José', reference: 'Génesis 45:7', passage: 'Y Dios me envió delante de vosotros, para preservaros vida.' },

  // ── RUT / ESTER / JOB (8) ──
  { quote: 'No me ruegues que te deje, y me aparte de ti; porque a dondequiera que tú fueres, iré yo.', options: ['Rut', 'Noemí', 'Ester', 'Orfa'], correct: 'Rut', reference: 'Rut 1:16', passage: 'No me ruegues que te deje, y me aparte de ti; porque a dondequiera que tú fueres, iré yo.' },
  { quote: 'Si perezco, perezco.', options: ['Ester', 'Rut', 'Débora', 'Sara'], correct: 'Ester', reference: 'Ester 4:16', passage: 'Voy a entrar al rey, lo cual no es conforme a la ley; y si perezco, perezco.' },
  { quote: 'Desnudo salí del vientre de mi madre, y desnudo volveré allá. Jehová dio, y Jehová quitó.', options: ['Job', 'David', 'Salomón', 'Eclesiastés'], correct: 'Job', reference: 'Job 1:21', passage: 'Desnudo salí del vientre de mi madre, y desnudo volveré allá. Jehová dio, y Jehová quitó; sea el nombre de Jehová bendito.' },
  { quote: 'Yo sé que mi Redentor vive, y al fin se levantará sobre el polvo.', options: ['Job', 'David', 'Isaías', 'Moisés'], correct: 'Job', reference: 'Job 19:25', passage: 'Yo sé que mi Redentor vive, y al fin se levantará sobre el polvo.' },
  { quote: 'He aquí, bienaventurado es el hombre a quien Dios castiga.', options: ['Job', 'David', 'Salomón', 'Elifaz'], correct: 'Elifaz', reference: 'Job 5:17', passage: 'He aquí, bienaventurado es el hombre a quien Dios castiga; por tanto, no menosprecies la corrección del Todopoderoso.' },
  { quote: 'En todo esto no pecó Job, ni atribuyó a Dios despropósito alguno.', options: ['Job', 'Moisés', 'David', 'Elí'], correct: 'Moisés', reference: 'Job 1:22', passage: 'En todo esto no pecó Job, ni atribuyó a Dios despropósito alguno.' },
  { quote: 'Jehová bendijo el postrer estado de Job más que el primero.', options: ['Job', 'Moisés', 'David', 'Salomón'], correct: 'Job', reference: 'Job 42:12', passage: 'Y bendijo Jehová el postrer estado de Job más que el primero.' },
  { quote: 'He aquí, yo soy sierva del Señor; hágase conmigo conforme a tu palabra.', options: ['María', 'Elisabet', 'Rut', 'Ana'], correct: 'María', reference: 'Lucas 1:38', passage: 'Entonces María dijo: He aquí la sierva del Señor; hágase conmigo conforme a tu palabra.' },
];

export function getRandomQuotes(count = 5) {
  const shuffled = [...quotes].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
