const verses = [
  {
    text: 'Porque de tal manera amó Dios al mundo, que ha dado a su Hijo unigénito, para que todo aquel que en él cree, no se pierda, mas tenga vida eterna.',
    book: 'Juan', chapter: 3, verse: 16,
    testament: 'Nuevo',
    aliases: ['San Juan 3'],
    explanation: 'El versículo más conocido de la Biblia resume el evangelio: Dios amó al mundo y envió a Su Hijo para salvar a todo el que cree.',
  },
  {
    text: 'Jehová es mi pastor; nada me faltará. En lugares de delicados pastos me hará descansar; junto a aguas de reposo me pastoreará.',
    book: 'Salmos', chapter: 23, verse: 1,
    testament: 'Antiguo',
    aliases: ['Salmo 23'],
    explanation: 'David describe a Dios como su pastor, confiando en Su provisión, guía y cuidado constante.',
  },
  {
    text: 'Porque yo sé los pensamientos que tengo acerca de vosotros, dice Jehová, pensamientos de paz, y no de mal, para daros el fin que esperáis.',
    book: 'Jeremías', chapter: 29, verse: 11,
    testament: 'Antiguo',
    aliases: [],
    explanation: 'Dios promete a Su pueblo en el exilio que tiene planes de bien y esperanza para ellos.',
  },
  {
    text: 'Y sabemos que a los que aman a Dios, todas las cosas les ayudan a bien, esto es, a los que conforme a su propósito son llamados.',
    book: 'Romanos', chapter: 8, verse: 28,
    testament: 'Nuevo',
    aliases: [],
    explanation: 'Pablo asegura que Dios obra en todas las circunstancias para el bien de quienes le aman.',
  },
  {
    text: 'Todo lo puedo en Cristo que me fortalece.',
    book: 'Filipenses', chapter: 4, verse: 13,
    testament: 'Nuevo',
    aliases: [],
    explanation: 'Pablo declara su total dependencia de Cristo para enfrentar cualquier circunstancia.',
  },
  {
    text: 'Fíate de Jehová de todo tu corazón, y no te apoyes en tu propia prudencia. Reconócelo en todos tus caminos, y él enderezará tus veredas.',
    book: 'Proverbios', chapter: 3, verses: '5-6',
    testament: 'Antiguo',
    aliases: [],
    explanation: 'Salomón enseña la confianza total en Dios como camino de sabiduría y dirección.',
  },
  {
    text: 'Pero los que esperan a Jehová tendrán nuevas fuerzas; levantarán alas como las águilas; correrán, y no se cansarán; caminarán, y no se fatigarán.',
    book: 'Isaías', chapter: 40, verse: 31,
    testament: 'Antiguo',
    aliases: [],
    explanation: 'Isaías promete renovación sobrenatural para quienes ponen su esperanza en Dios.',
  },
  {
    text: 'Lámpara es a mis pies tu palabra, y lumbrera a mi camino.',
    book: 'Salmos', chapter: 119, verse: 105,
    testament: 'Antiguo',
    aliases: ['Salmo 119'],
    explanation: 'El salmista reconoce la Palabra de Dios como guía indispensable para la vida.',
  },
  {
    text: 'Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar.',
    book: 'Mateo', chapter: 11, verse: 28,
    testament: 'Nuevo',
    aliases: ['San Mateo 11'],
    explanation: 'Jesús extiende una invitación de descanso y alivio a todos los que sufren.',
  },
  {
    text: 'Mira que te mando que te esfuerces y seas valiente; no temas ni desmayes, porque Jehová tu Dios estará contigo en dondequiera que vayas.',
    book: 'Josué', chapter: 1, verse: 9,
    testament: 'Antiguo',
    aliases: [],
    explanation: 'Dios anima a Josué al comenzar su liderazgo, prometiendo Su presencia constante.',
  },
  {
    text: 'Si se humillare mi pueblo, sobre el cual mi nombre es invocado, y oraren, y buscaren mi rostro, y se convirtieren de sus malos caminos, entonces yo oiré desde los cielos, y perdonaré sus pecados, y sanaré su tierra.',
    book: '2 Crónicas', chapter: 7, verse: 14,
    testament: 'Antiguo',
    aliases: ['2 Crónicas 7'],
    explanation: 'Dios promete restauración si Su pueblo se humilla, ora y se vuelve a Él.',
  },
  {
    text: 'Si confesares con tu boca al Señor Jesús, y creyeres en tu corazón que Dios le levantó de los muertos, serás salvo.',
    book: 'Romanos', chapter: 10, verse: 9,
    testament: 'Nuevo',
    aliases: [],
    explanation: 'Pablo explica el camino de salvación mediante la confesión y la fe en Cristo resucitado.',
  },
  {
    text: 'Yo soy el camino, y la verdad, y la vida; nadie viene al Padre, sino por mí.',
    book: 'Juan', chapter: 14, verse: 6,
    testament: 'Nuevo',
    aliases: ['San Juan 14'],
    explanation: 'Jesús declara ser la única vía para llegar a Dios Padre.',
  },
  {
    text: 'En el principio creó Dios los cielos y la tierra.',
    book: 'Génesis', chapter: 1, verse: 1,
    testament: 'Antiguo',
    aliases: [],
    explanation: 'El primer versículo de la Biblia establece a Dios como Creador de todo lo que existe.',
  },
  {
    text: 'Mas buscad primeramente el reino de Dios y su justicia, y todas estas cosas os serán añadidas.',
    book: 'Mateo', chapter: 6, verse: 33,
    testament: 'Nuevo',
    aliases: ['San Mateo 6'],
    explanation: 'Jesús enseña a priorizar el reino de Dios sobre las preocupaciones materiales.',
  },
  {
    text: 'Y ahora permanecen la fe, la esperanza y el amor, estos tres; pero el mayor de ellos es el amor.',
    book: '1 Corintios', chapter: 13, verse: 13,
    testament: 'Nuevo',
    aliases: ['1 Corintios 13', 'Primera Corintios 13'],
    explanation: 'Pablo concluye que el amor es la virtud más grande y eterna.',
  },
  {
    text: 'Por cuanto todos pecaron, y están destituidos de la gloria de Dios.',
    book: 'Romanos', chapter: 3, verse: 23,
    testament: 'Nuevo',
    aliases: [],
    explanation: 'Pablo declara la condición universal de pecado de toda la humanidad.',
  },
  {
    text: 'Enjugará Dios toda lágrima de los ojos de ellos; y ya no habrá muerte, ni habrá más llanto, ni clamor, ni dolor; porque las primeras cosas pasaron.',
    book: 'Apocalipsis', chapter: 21, verse: 4,
    testament: 'Nuevo',
    aliases: ['Apocalipsis 21'],
    explanation: 'Juan describe la esperanza del nuevo cielo y nueva tierra donde Dios eliminará todo sufrimiento.',
  },
  {
    text: 'Dios es nuestro amparo y fortaleza, nuestro pronto auxilio en las tribulaciones.',
    book: 'Salmos', chapter: 46, verse: 1,
    testament: 'Antiguo',
    aliases: ['Salmo 46'],
    explanation: 'El salmista proclama a Dios como refugio seguro en tiempos de angustia.',
  },
  {
    text: 'Alzaré mis ojos a los montes; ¿de dónde vendrá mi socorro? Mi socorro viene de Jehová, que hizo los cielos y la tierra.',
    book: 'Salmos', chapter: 121, verses: '1-2',
    testament: 'Antiguo',
    aliases: ['Salmo 121'],
    explanation: 'El salmista afirma que su ayuda proviene del Creador del cielo y la tierra.',
  },
];

export function getRandomVerse() {
  return verses[Math.floor(Math.random() * verses.length)];
}
